[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads/"
startup_command = "ls"

[[session]]
name = "wezterm config"
path = "~/.config/wezterm"
startup_command = "nvim wezterm.lua"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "Dev ğŸ’»"
path = "~/dev"
startup_command = "l"

[[session]]
name = "Home ğŸ¡"
path = "~/"
startup_command = "clear"


[[session]]
name = "Old Notes"
path = "~/OneDrive/Second Brain/"
startup_command = "nvim"

[[session]]
name = "Second Brain ğŸ§ "
path = "~/Documents/Second Brain/"
startup_command = "nvim"
