[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads/"
startup_command = "ls"

[[session]]
name = "wezterm ğŸ”§"
path = "~/.config/wezterm"
startup_command = "nvim wezterm.lua"

[[session]]
name = "nvim ğŸ”§"
path = "~/.config/nvim"
startup_command = "nvim "

[[session]]
name = "karabinar ğŸ”§"
path = "~/.config/karabinar"
startup_command = "nvim"

[[session]]
name = "scripts ğŸ”§"
path = "~/local/bin"
startup_command = "nvim"

[[session]]
name = "sesh ğŸ”§"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "Dev ğŸ’»"
path = "~/dev"
startup_command = "l"

[[session]]
name = "Home ğŸ¡"
path = "~/"
startup_command = "clear"
